# Generated by Django 6.0.3 on 2026-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('cake_size', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('delivery_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom_cakes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
